name: ndu_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  file_picker: '>=8.1.2'
  go_router: ^17.0.0
  url_launcher: ^6.0.0
  google_sign_in: '>=6.2.1'
  firebase_auth: '>=5.3.3'
  cloud_firestore: '>=5.5.0'
  firebase_storage: '>=13.0.0'
  shimmer: ^3.0.0
  http: ^1.0.0
  flutter_svg: ^2.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  firebase_core: ^4.2.0
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  intl: ^0.20.2
  flutter_appauth: ^6.0.0
  flutter_secure_storage: ^9.0.0
  flutter_markdown: ^0.7.2
  pdf: ^3.10.8
  printing: ^5.13.4
  webview_flutter: ^4.7.0
  webview_flutter_web: ^0.2.3+4
  webview_flutter_platform_interface: ^2.6.0
  flutter_native_splash: ^2.3.0
  smooth_page_indicator: ^1.1.0

  vector_math: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/config/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-LightItalic.otf
          weight: 300
          style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFD700"
  color_dark: "#1A1A1A"
  image: assets/images/ndu_logo_splash.png
  android: true
  ios: true
  web: false
